create table cliente (
	codcliente INT PRIMARY KEY,
	nome VARCHAR(50),
	sexo VARCHAR(50),
	dt_nascimento DATE,
	bairro VARCHAR(23)
);
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (1, 'Walker Dales', 'M', '1945/08/05', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (2, 'Chastity Macbane', 'F', '1974/02/18', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (3, 'Cordelia Ledley', 'F', '2007/12/21', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (4, 'Garnette Peaddie', 'F', '1947/09/30', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (5, 'Nicolais Forgan', 'M', '1957/10/10', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (6, 'Nikolia Tatershall', 'F', '1996/05/16', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (7, 'Ewart Cathee', 'M', '1997/06/18', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (8, 'Gillian Stuck', 'F', '2010/09/09', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (9, 'Fowler Garling', 'M', '1954/11/19', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (10, 'Urbanus Thewys', 'M', '2000/04/09', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (11, 'Gerrilee Cohn', 'F', '2001/02/09', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (12, 'Xylina Scoyne', 'F', '1983/04/08', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (13, 'Margeaux Surgood', 'F', '2005/07/06', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (14, 'Bartholemy Toward', 'M', '1966/08/11', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (15, 'Barbara Hallad', 'F', '1982/09/19', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (16, 'Regan Royse', 'M', '1996/12/16', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (17, 'Cherish Garvan', 'F', '1989/12/25', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (18, 'Marty Peppard', 'M', '1945/09/11', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (19, 'Reade Ragsdall', 'M', '1949/12/31', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (20, 'Abbi Ellam', 'F', '1996/12/23', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (21, 'Drusi Diggins', 'F', '1984/11/21', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (22, 'Olga Curdell', 'F', '1974/10/06', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (23, 'Ralph Parley', 'M', '1977/12/07', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (24, 'Sayers Allday', 'M', '1946/07/14', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (25, 'Calli Pyatt', 'F', '1961/03/21', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (26, 'Fran Ranstead', 'F', '2009/02/22', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (27, 'Antonie Ricciardiello', 'F', '2001/04/01', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (28, 'Mohandis Keable', 'M', '1957/04/07', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (29, 'Edgardo McGraw', 'M', '1996/01/27', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (30, 'Baillie Aluard', 'M', '1991/10/06', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (31, 'Farah Melarkey', 'F', '1973/01/09', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (32, 'Zack Reinard', 'M', '1967/10/16', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (33, 'Ollie Mordaunt', 'F', '1973/10/01', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (34, 'Isa Brisset', 'M', '1997/06/21', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (35, 'Clara Le Port', 'F', '1994/05/26', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (36, 'Gilberto Suggitt', 'M', '1982/11/22', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (37, 'Frederik Farnham', 'M', '1967/11/26', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (38, 'Alix Schapero', 'F', '1978/02/28', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (39, 'Maurits Lindwasser', 'M', '1964/10/21', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (40, 'Dennet Bailes', 'M', '1987/04/19', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (41, 'Haslett Clout', 'M', '2009/11/27', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (42, 'Anne-marie Ewing', 'F', '1960/10/05', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (43, 'Brew Gilhooly', 'M', '1969/02/03', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (44, 'Dorene Gero', 'F', '2004/05/29', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (45, 'Lorilee Towns', 'F', '1946/06/07', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (46, 'Briny MacQuist', 'F', '2007/01/05', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (47, 'Montague Bonhill', 'M', '1961/06/25', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (48, 'Addie Dahlgren', 'F', '1961/02/01', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (49, 'Pegeen Probetts', 'F', '1983/01/22', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (50, 'Marita Whitworth', 'F', '1975/08/13', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (51, 'Sari Stiant', 'F', '1956/05/30', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (52, 'Joel McBean', 'M', '1980/06/06', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (53, 'Carter Burds', 'M', '1999/04/18', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (54, 'Andy Yitzhakov', 'M', '1968/03/25', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (55, 'Cyrille Castille', 'M', '1981/01/13', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (56, 'Salomon Tute', 'M', '1973/05/14', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (57, 'Leonerd Spurgeon', 'M', '1983/11/21', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (58, 'Brice Agius', 'M', '2002/02/17', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (59, 'Early McBeith', 'M', '1945/01/01', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (60, 'Dalis Humbatch', 'M', '1978/07/24', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (61, 'Benjie Trenholm', 'M', '1950/10/26', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (62, 'Maureene Escreet', 'F', '1958/10/30', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (63, 'North Savell', 'M', '1963/11/15', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (64, 'Kristina Azema', 'F', '1956/01/01', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (65, 'Christoper Dible', 'M', '1998/07/24', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (66, 'Kelley Filipczak', 'M', '1960/01/26', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (67, 'Nero Grayston', 'M', '1962/09/20', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (68, 'Elysee Mapletoft', 'F', '2009/06/22', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (69, 'Ikey Thomel', 'M', '1971/08/13', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (70, 'Fiorenze Fendlow', 'F', '1958/03/28', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (71, 'Gaston Dix', 'M', '1983/04/03', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (72, 'Falkner Hurdle', 'M', '1999/07/20', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (73, 'Hillie Martignoni', 'M', '1998/02/05', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (74, 'Dasie Kahane', 'F', '2001/12/17', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (75, 'Carena Davitt', 'F', '1999/07/23', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (76, 'Jermaine McLurg', 'F', '1952/10/20', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (77, 'Nerta Oldis', 'F', '1996/09/26', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (78, 'Jayne Deer', 'F', '1957/02/12', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (79, 'Alissa Bellerby', 'F', '2003/08/13', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (80, 'Sarette Pobjoy', 'F', '1981/10/29', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (81, 'Arda MacCauley', 'F', '1964/06/19', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (82, 'Netti Narraway', 'F', '1986/04/23', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (83, 'Stephana Page', 'F', '1991/10/16', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (84, 'Latrena Dovidian', 'F', '1999/11/23', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (85, 'Marlin Micheau', 'M', '1967/04/29', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (86, 'Kelbee Lory', 'M', '1983/10/26', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (87, 'Afton O''Regan', 'F', '2010/10/07', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (88, 'Sol Coxen', 'M', '1989/04/07', 'Pauliceia');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (89, 'Lay Blasdale', 'M', '1960/09/24', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (90, 'Kylie Reichelt', 'M', '1987/10/04', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (91, 'Harper Douche', 'M', '1985/11/23', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (92, 'Sarge Dumke', 'M', '1946/12/15', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (93, 'Foss Waldocke', 'M', '1982/07/07', 'Vinte e Cinco de Agosto');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (94, 'Abramo Garci', 'M', '1957/01/13', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (95, 'Padraig Ithell', 'M', '1998/05/15', 'Vila Leopoldina');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (96, 'Barnard Rahl', 'M', '2000/02/22', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (97, 'Idalia Callaghan', 'F', '1976/04/08', 'Parque Lafaiete');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (98, 'Bobina Magnar', 'F', '1959/12/14', 'Vila São Luis');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (99, 'Jennette Frushard', 'F', '2004/07/16', 'Centro');
insert into cliente (codcliente, nome, sexo, dt_nascimento, bairro) values (100, 'Lamond Farnworth', 'M', '1973/01/01', 'Vila São Luis');
